{{- range .Values.usernames }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "code-server.fullname" . }}
  namespace: {{ .name }}
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
{{- end }}
