apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default

  destination:
    namespace: argocd

  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: v7.6.12
      helm:
        valueFiles:
          - $values/apps/argocd.values.yaml
    - repoURL: dummy    # overwritten by kommon
      ref: values
