apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: cert-manager
  sources:
    - repoURL: 'https://charts.jetstack.io'
      chart: cert-manager
      targetRevision: v1.16.1
      helm:
        valueFiles:
          - $values/apps/cert-manager.values.yaml
    - repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/main_org/main.git'
      targetRevision: master
      ref: values
