apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "v1.15.1"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1h
  install:
    createNamespace: true
  install:
    crds: Create
  upgrade:
    crds: Skip
  values:
    installCRDs: true
