apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-stacks
  namespace: argocd
spec:
  project: default

  destination:
    namespace: argocd

  source:
    repoURL: dummy
    ref: values
    path: apps/dev-stacks
