apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gitea
  sources:
    - repoURL: 'https://dl.gitea.com/charts/'
      chart: gitea
      targetRevision: 12.4.0
      helm:
        valueFiles:
          - $values/apps/gitea.values.yaml
    - repoURL: 'http://gitea-http.gitea.svc.cluster.local:3000/main_org/main.git'
      targetRevision: master
      ref: values
