apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default

  destination:
    namespace: gitea

  sources:
    - repoURL: https://dl.gitea.com/charts/
      chart: gitea
      targetRevision: 12.4.0
      helm:
        valueFiles:
          - $values/apps/gitea.values.yaml
    - repoURL: dummy
      ref: values
