apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: longhorn
  chart:
    spec:
      chart: longhorn
      version: "1.7.2"
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 1h
  install:
    createNamespace: true
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
    defaultSettings:
      defaultReplicaCount: 1
      createDefaultDiskLabeledNodes: true
      defaultDataPath: /var/mnt/longhorn
    csi:
      kubeletRootDir: /var/lib/kubelet
    # Trigger reconciliation

