apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: postgres-operator
  chart:
    spec:
      chart: postgres-operator
      version: "1.14.0"
      sourceRef:
        kind: HelmRepository
        name: zalando
      interval: 1h
  install:
    createNamespace: true
